name = "youtube-transcript-worker"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[vars]
GEMINI_API_KEY = "AIzaSyAYDXb6dkr9C7oscsF5KJ0TXoYy-F6f6is"  # Will be set in the Cloudflare dashboard

# Define KV namespace for caching
 kv_namespaces = [
   { binding = "TRANSCRIPT_CACHE", id = "", preview_id = "e98c7000f28042218e822a9c5a8fa03b" }
 ]